yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
# from django.core.exceptions import ValidationError

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Имя', max_length=200)
    slug = models.SlugField('url', unique=True)
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):

    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Опубликовано', auto_now_add=True)
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        # return str(self.text)[:30] + '...'
        return str(self.text)[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Пост',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField('Текст')
    created = models.DateTimeField('Опубликовано', auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return str(self.text)[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_follow'
            ),
            models.CheckConstraint(
                check=models.Q(_negated=True, user=models.F('author')),
                name='author_and_follower_can_not_be_equal'
            )
        )

    def __str__(self):
        return str(f'{self.user.username}->{self.author.username}')

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'text',
            'group',
            'image'
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.utils import IntegrityError
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
# from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post

POSTS_TO_SHOW = settings.POSTS_TO_SHOW
User = get_user_model()

TEMPLATES = {
    'index': 'posts/index.html',
    'group_list': 'posts/group_list.html',
    'profile': 'posts/profile.html',
    'post_detail': 'posts/post_detail.html',
    'create_post': 'posts/create_post.html',
    'follow': 'posts/follow.html'
}

CACHE_KEYS = {
    'index': 'index-{page}',
    'follow': 'follow-{user}',
    'group_posts': '{slug}-posts-{page}',
    'author_posts': '{author}-posts-{page}',
}


def paginator(posts, page_number):
    pag = Paginator(posts, POSTS_TO_SHOW)
    page_obj = pag.get_page(page_number)
    return page_obj


def index(request):
    """
    Вывод постов на главной странице.
    Кэш работает по страницам пагинации.
    """
    page_number = request.GET.get('page')
    page_obj = cache.get(CACHE_KEYS['index'].format(page=page_number))

    if not page_obj:
        page_obj = paginator(
            Post.objects.all()
            .select_related(
                'author',
                'group'
            ),
            page_number
        )
        cache.set(CACHE_KEYS['index'].format(page=page_number), page_obj)

    context = {
        'page_obj': page_obj,
    }
    return render(request, TEMPLATES['index'], context)


def group_posts(request, slug):
    """
    Вывод постов одной группы.
    Кэш работает по страницам пагинации.
    """
    page_number = request.GET.get('page')
    page_obj = cache.get(
        CACHE_KEYS['group_posts'].format(
            slug=slug,
            page=page_number
        )
    )
    if not page_obj:
        page_obj = paginator(
            get_object_or_404(
                Group,
                slug=slug
            ).posts.all().prefetch_related('author'),
            page_number
        )
        cache.set(
            CACHE_KEYS['group_posts'].format(
                slug=slug,
                page=page_number
            ),
            page_obj
        )
    group = None

    if page_obj.object_list.count() > 1:
        group = page_obj.object_list[0].group
    else:
        group = get_object_or_404(Group, slug=slug)

    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, TEMPLATES['group_list'], context)


# cache author and author_posts
def profile(request, username):
    page_number = request.GET.get('page')
    author = get_object_or_404(User, username=username)
    posts = author.posts.all().prefetch_related('group')
    posts_count = posts.count

    page_obj = paginator(
        posts,
        page_number
    )

    following = True if (
        request.user.is_authenticated
        and author.following.filter(user=request.user).exists()
    ) else False

    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
        'posts_count': posts_count
    }
    return render(request, TEMPLATES['profile'], context)


# cache post, comments
def post_detail(request, post_id):
    post = get_object_or_404(
        Post.objects.select_related(
            'author',
            'group',
        ),
        pk=post_id
    )
    is_edit_allowed = True if (
        request.user == post.author
    ) else False
    context = {
        'post': post,
        'form': CommentForm(
            request.POST or None
        ),
        'is_edit_allowed': is_edit_allowed,
    }
    return render(request, TEMPLATES['post_detail'], context)


# clear cache of group author
@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            author = request.user
            post.author = author
            post.save()
            return redirect(reverse('posts:profile', args=(author.username,)))

    context = {
        'form': form
    }
    return render(request, TEMPLATES['create_post'], context)


# clear cache of group if required
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        return redirect(reverse('posts:post_detail', args=(post_id,)))

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('posts:post_detail', args=(post_id,)))

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, TEMPLATES['create_post'], context)


# clear cache comment post
@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """
    Вывод постов всех авторов, на которых подписан текущий пользователь.
    Добавлены: пагинация, кэш.
    """
    page_number = request.GET.get('page')
    posts = cache.get(CACHE_KEYS['follow'].format(user=request.user))
    if not posts:
        posts = Post.objects.filter(
            author__following__user=request.user
        ).select_related('author', 'group',)
        cache.set(CACHE_KEYS['follow'].format(user=request.user), posts)

    page_obj = paginator(posts, page_number)

    context = {
        'page_obj': page_obj,
    }
    return render(request, TEMPLATES['follow'], context)


@login_required
def profile_follow(request, username):
    """
    Подписка на автора.
    Добавлены: кэш.
    """
    try:
        Follow.objects.create(
            author=get_object_or_404(User, username=username),
            user=request.user,
        )
        cache.delete(CACHE_KEYS['follow'].format(user=request.user))
    except IntegrityError as e:
        raise Http404(e.__cause__)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """
    Отписка от автора.
    Добавлены: кэш.
    """
    get_object_or_404(
        Follow,
        user=request.user,
        author=User.objects.get(username=username)
    ).delete()
    cache.delete(CACHE_KEYS['follow'].format(user=request.user))
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактирование поста
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% include "includes/form_errors.html" %}
          {% endif %}
          <form method="post" enctype="multipart/form-data"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% include "includes/form.html" %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %} Ваши подписки на авторов {% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    <h1>Посты ваших любимых авторов</h1>
    {% for post in page_obj %}
      {% include "posts/includes/show_post.html" %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include "posts/includes/paginator.html" %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{group.title}}</h1>
    {{ group.description|linebreaks }}
    {% for post in page_obj %}
      {% include "posts/includes/show_post.html" %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include "posts/includes/paginator.html" %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'posts/includes/switcher.html' %}
    <h1>Последние обновления на сайте</h1>
      {% for post in page_obj %}
        {% include "posts/includes/show_post.html" %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      {% include "posts/includes/paginator.html" %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{post.text|slice:":30"}}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }} <br>
              <a href="{% url 'posts:group_list' post.group.slug %}">
                Все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:<span>{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              Все посты пользователя
            </a>
          </li>
          {% if is_edit_allowed %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <a href="{% url 'posts:post_edit' post.pk %}">
                Редактировать
              </a>
            </li>
          {% endif %}
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        {{ post.text|linebreaks }}
        {% load user_filters %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}
        {% for comment in post.comments.all %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                {{ comment.text }}
                </p>
            </div>
          </div>
        {% endfor %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ posts_count }}</h3>
      {% if user.is_authenticated %}
        {% if user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
    {% for post in page_obj %}
      {% include "posts/includes/show_post.html" %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include "posts/includes/paginator.html" %}
  </div>
{% endblock %}